FROM golang:1.7

ADD . /go/src/github.com/das08/kuRakutanBot-go
WORKDIR /go/src/github.com/das08/kuRakutanBot-go

#RUN mkdir go/src/github.com/das08/kuRakutanBot-go

#WORKDIR /go/src/github.com/das08/kuRakutanBot-go

#COPY . /go/src/github.com/das08/kuRakutanBot-go
