version: '3'
services:
    app:
        build:
            context: .
            dockerfile: ./build/Dockerfile
        tty: true
        volumes:
            - ./cmd/app:/go/src/github.com/das08/kuRakutanBot-go