version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    tty: true
    volumes:
       - ./cmd/app:/go/src/github.com/das08/kuRakutanBot-go
       
  mongo:
    image: mongo:4.4.5
    #restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
      - ./configdb:/data/configdb

  mongo-express:
    image: mongo-express:0.54
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASS}