version: '3.8'
services:
  app:
    container_name: rakutan-app
    build:
      context: ./src/app
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - ./src/app:/usr/src/app
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8081"

  postgres:
    container_name: rakutan-db
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:6.2.6
    container_name: rakutan-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6379:6379"


volumes:
  postgres:
  redis: