version: '3.8'

networks:
  grafana:
  rakutan:

services:
  rakutan-bot:
    container_name: rakutan-app
    networks:
      - rakutan
    build:
      context: ./src/app
      dockerfile: Dockerfile
    restart: always
    tty: true
    volumes:
      - dbsocket:/var/run/postgresql
      - ./src/app:/usr/src/app
    depends_on:
      - postgres
      - redis
    ports:
      - "127.0.0.1:6060:6060"
      - "127.0.0.1:8081:8081"
      - "127.0.0.1:8082:8082"

  postgres:
    image: postgres:14.4-alpine
    container_name: rakutan-db
    networks:
      - grafana
      - rakutan
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - postgres:/var/lib/postgresql/data
      - dbsocket:/var/run/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/conf/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  redis:
    image: redis:7-alpine
    container_name: rakutan-redis
    networks:
      - rakutan
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

  kuwiki-mock:
    container_name: kuwiki-mock
    networks:
      - rakutan
    build:
      context: ./src/kuwiki-mock
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports:
      - "127.0.0.1:8000:8000"
    profiles:
      - mock

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    profiles:
      - metrics
    volumes:
      - ./src/grafana:/etc/grafana/provisioning/
      - grafana:/var/lib/grafana

  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    networks:
      - grafana
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    profiles:
      - metrics
    volumes:
      - influx:/var/lib/influxdb

volumes:
  postgres:
  redis:
  dbsocket:
  influx:
  grafana: