version: '3.8'
services:
  app:
    container_name: kuRakutanBot-go
    build:
      context: ./src/app
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    depends_on:
      - mongo
      - redis
    ports:
      - "8081:8081"
       
  mongo:
    container_name: mongodb
    image: mongo:5.0.6-focal
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - "27018:27017"
    volumes:
      - type: bind
        source: ./docker/db/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
      - type: volume
        source: mongo
        target: /data/db
        volume:
          nocopy: true
      - type: volume
        source: mongo
        target: /data/configdb
        volume:
          nocopy: true

  redis:
    image: redis:6.2.6
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    ports:
      - "6379:6379"

volumes:
  mongo:
  redis: