package flexmessage

import "github.com/line/line-bot-sdk-go/v7/linebot"

func LoadOmikuji10() *linebot.BubbleContainer {
	container := &linebot.BubbleContainer{
		Type: linebot.FlexContainerTypeBubble,
		Header: &linebot.BoxComponent{
			Type:   linebot.FlexComponentTypeBox,
			Layout: linebot.FlexBoxLayoutTypeVertical,
			Contents: []linebot.FlexComponent{
				&linebot.BoxComponent{
					Type:   linebot.FlexComponentTypeBox,
					Layout: linebot.FlexBoxLayoutTypeHorizontal,
					Contents: []linebot.FlexComponent{
						&linebot.TextComponent{
							Type:   linebot.FlexComponentTypeText,
							Text:   "🎊10連！らくたんおみくじ🎊",
							Weight: linebot.FlexTextWeightTypeBold,
							Color:  "#ffc107",
							Size:   linebot.FlexTextSizeTypeSm,
							Wrap:   true,
							Align:  linebot.FlexComponentAlignTypeCenter,
						},
					},
				},
			},
			Spacing:       linebot.FlexComponentSpacingTypeMd,
			PaddingTop:    "18px",
			PaddingBottom: "18px",
		},
		Body: &linebot.BoxComponent{
			Type:   linebot.FlexComponentTypeBox,
			Layout: linebot.FlexBoxLayoutTypeVertical,
			Contents: []linebot.FlexComponent{
				&linebot.BoxComponent{
					Type:   linebot.FlexComponentTypeBox,
					Layout: linebot.FlexBoxLayoutTypeHorizontal,
					Contents: []linebot.FlexComponent{
						&linebot.TextComponent{
							Type:  linebot.FlexComponentTypeText,
							Text:  "おみくじ結果",
							Size:  linebot.FlexTextSizeTypeXxs,
							Color: "#aaaaaa",
							Flex:  toIntPtr(0),
						},
					},
				},
				&linebot.BoxComponent{
					Type:   linebot.FlexComponentTypeBox,
					Layout: linebot.FlexBoxLayoutTypeVertical,
					Margin: linebot.FlexComponentMarginTypeMd,
					Contents: []linebot.FlexComponent{
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
						&linebot.BoxComponent{
							Type:   linebot.FlexComponentTypeBox,
							Layout: linebot.FlexBoxLayoutTypeHorizontal,
							Contents: []linebot.FlexComponent{
								&linebot.TextComponent{
									Type:   linebot.FlexComponentTypeText,
									Text:   "SSS",
									Flex:   toIntPtr(2),
									Size:   linebot.FlexTextSizeTypeSm,
									Weight: linebot.FlexTextWeightTypeBold,
									Color:  "#c3c45b",
									Align:  linebot.FlexComponentAlignTypeStart,
									Style:  linebot.FlexTextStyleTypeItalic,
								},
								&linebot.TextComponent{
									Type:  linebot.FlexComponentTypeText,
									Text:  "LectureName",
									Size:  linebot.FlexTextSizeTypeSm,
									Color: "#666666",
									Flex:  toIntPtr(11),
									Wrap:  true,
								},
								&linebot.TextComponent{
									Type:       linebot.FlexComponentTypeText,
									Text:       "選択",
									Size:       linebot.FlexTextSizeTypeMd,
									Color:      "#4c7cf5",
									Align:      linebot.FlexComponentAlignTypeEnd,
									Weight:     linebot.FlexTextWeightTypeBold,
									Decoration: linebot.FlexTextDecorationTypeUnderline,
									Action: &linebot.MessageAction{
										Label: "action",
										Text:  "#123456",
									},
									OffsetBottom: "3px",
									Flex:         toIntPtr(2),
								},
							},
							Margin: linebot.FlexComponentMarginTypeLg,
						},
					},
				},
			},
		},
		Styles: &linebot.BubbleStyle{
			Header: &linebot.BlockStyle{
				BackgroundColor: "#3C3C3A",
			},
			Body: &linebot.BlockStyle{
				BackgroundColor: "#F4F3F9",
			},
			Footer: &linebot.BlockStyle{
				Separator:       true,
				BackgroundColor: "#E7E8E3",
				SeparatorColor:  "#D6D6D4",
			},
		},
	}
	return container
}
